// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Aberta de propósito, para um orquestrador sem token conseguir perguntar. Diz também qual aplicação e versão respondeu.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Liveness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.Status"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Devolve quem chamou, como o realm descreveu: subject, username, e-mail e papéis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "Quem sou eu",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.Principal"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        },
        "/wagering/transactions": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Aplica BET, WIN, LOSS, REFUND ou ROLLBACK a uma carteira, uma única vez, por mais que seja reenviada. O header Idempotency-Key é obrigatório e nunca é substituído pelo servidor. Mesma chave e mesmo conteúdo devolvem o resultado gravado, com o saldo observado no processamento original (200 ou 422, com idempotentReplay true). Mesma chave com outro conteúdo, ou a mesma operação sob outra chave, é 409. O providerId do corpo precisa ser o do token.\nDistinguível pelo status: 200 processada, 202 aguardando referência, 400 entrada inválida (nada gravado), 409 conflito de idempotência, 422 rejeição de negócio (com failureCode, gravada e reproduzível), 503 indisponibilidade transitória (tente de novo).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wagering"
                ],
                "summary": "Envia uma operação de um provedor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chave escolhida pelo provedor, por exemplo provider-a:transaction-123",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "A operação",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wagering.SubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wagering.TransactionResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/wagering.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/wagering.TransactionResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        },
        "/wallets": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Cria a carteira na moeda do saldo inicial. Com saldo positivo, cria também a transação OPENING, o crédito no ledger e os eventos, no mesmo commit. Com saldo zero, cria só a carteira. Restrita ao serviço interno.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Abre a carteira de um jogador",
                "parameters": [
                    {
                        "description": "Jogador e saldo inicial",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wallet.OpenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/wallet.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.Status": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "server"
                },
                "service": {
                    "type": "string",
                    "example": "pedro-test-server"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.4.0"
                }
            }
        },
        "structs.APIError": {
            "type": "object",
            "properties": {
                "failureCode": {
                    "description": "FailureCode is the stable, documented reason of a business rejection or of an invalid\noperation. It is what a provider reads to tell an input it can correct from a definitive\noutcome, and it is absent on errors that are not about the operation itself.",
                    "type": "string",
                    "example": "INSUFFICIENT_FUNDS"
                },
                "message": {
                    "type": "string",
                    "example": "invalid token"
                }
            }
        },
        "structs.MoneyDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "25.00"
                },
                "currency": {
                    "type": "string",
                    "example": "BRL"
                }
            }
        },
        "structs.Principal": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "provider_id": {
                    "description": "ProviderID is the provider this identity acts as, from the provider_id claim of its\ntoken. It is empty for anyone that is not a provider. The provider a request may act for\ncomes from here and never from what the request says about itself.",
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sub": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "wagering.SubmitRequest": {
            "type": "object",
            "properties": {
                "externalTransactionId": {
                    "type": "string",
                    "example": "transaction-123"
                },
                "gameId": {
                    "type": "string",
                    "example": "fortune-chimp"
                },
                "kind": {
                    "type": "string",
                    "enum": [
                        "BET",
                        "WIN",
                        "LOSS",
                        "REFUND",
                        "ROLLBACK"
                    ],
                    "example": "BET"
                },
                "money": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "playerId": {
                    "type": "string",
                    "example": "0192f28f-5dc0-7d58-bdb2-814ad6a0f4a1"
                },
                "providerId": {
                    "type": "string",
                    "example": "provider-a"
                },
                "referenceExternalTransactionId": {
                    "type": "string",
                    "example": "transaction-122"
                },
                "roundId": {
                    "type": "string",
                    "example": "round-987"
                },
                "walletId": {
                    "type": "string",
                    "example": "0192f291-27dd-7d3f-8071-5f8685deef37"
                }
            }
        },
        "wagering.TransactionResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "failureCode": {
                    "type": "string",
                    "example": "INSUFFICIENT_FUNDS"
                },
                "idempotentReplay": {
                    "type": "boolean",
                    "example": false
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "PROCESSED",
                        "REJECTED",
                        "PENDING_REFERENCE",
                        "FAILED"
                    ],
                    "example": "PROCESSED"
                },
                "transactionId": {
                    "type": "string",
                    "example": "0192f298-345e-7e38-af88-e43f851a819d"
                }
            }
        },
        "wallet.OpenRequest": {
            "type": "object",
            "properties": {
                "initialBalance": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "playerId": {
                    "type": "string",
                    "example": "0192f28f-5dc0-7d58-bdb2-814ad6a0f4a1"
                }
            }
        },
        "wallet.Response": {
            "type": "object",
            "properties": {
                "balance": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "id": {
                    "type": "string",
                    "example": "0192f291-27dd-7d3f-8071-5f8685deef37"
                },
                "playerId": {
                    "type": "string",
                    "example": "0192f28f-5dc0-7d58-bdb2-814ad6a0f4a1"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "http://localhost:8080/realms/pedro-test/protocol/openid-connect/token",
            "scopes": {
                "openid": "Acesso à API"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "pedro-test",
	Description:      "Carteiras de jogadores e operações de provedores de jogos: apostas, prêmios, derrotas, estornos e reversões.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
