// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "O processo está de pé. Não olha para nenhuma dependência: um processo vivo que não alcança o banco deve sair de rotação, não ser morto. Aberta de propósito, para um orquestrador sem token conseguir perguntar. ` + "`" + `/health` + "`" + ` é o mesmo probe, com o nome que a infraestrutura já usa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Liveness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.Status"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "O processo está de pé. Não olha para nenhuma dependência: um processo vivo que não alcança o banco deve sair de rotação, não ser morto. Aberta de propósito, para um orquestrador sem token conseguir perguntar. ` + "`" + `/health` + "`" + ` é o mesmo probe, com o nome que a infraestrutura já usa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Liveness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.Status"
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Pergunta ao PostgreSQL e ao SQS. 200 quando todos respondem, 503 quando algum não, com o estado de cada um. É o probe que decide se a instância recebe tráfego. Aberta de propósito.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operations"
                ],
                "summary": "Readiness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.Readiness"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/health.Readiness"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Devolve quem chamou, como o realm descreveu: subject, username, e-mail e papéis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "Quem sou eu",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.Principal"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        },
        "/providers/{providerId}/wagering/transactions/{externalTransactionId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "O providerId do caminho precisa ser o do token: outro é 403, decidido antes de tocar em qualquer dado.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wagering"
                ],
                "summary": "Lê uma transação pelo id do provedor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id do provedor, o mesmo do token",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Id que o provedor deu à transação",
                        "name": "externalTransactionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wagering.TransactionDetail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        },
        "/wagering/transactions": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Aplica BET, WIN, LOSS, REFUND ou ROLLBACK a uma carteira, uma única vez, por mais que seja reenviada. O header Idempotency-Key é obrigatório e nunca é substituído pelo servidor. Mesma chave e mesmo conteúdo devolvem o resultado gravado, com o saldo observado no processamento original (200 ou 422, com idempotentReplay true). Mesma chave com outro conteúdo, ou a mesma operação sob outra chave, é 409. O providerId do corpo precisa ser o do token.\nDistinguível pelo status: 200 processada, 202 aguardando referência, 400 entrada inválida (nada gravado), 409 conflito de idempotência, 422 rejeição de negócio (com failureCode, gravada e reproduzível), 503 indisponibilidade transitória (tente de novo).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wagering"
                ],
                "summary": "Envia uma operação de um provedor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chave escolhida pelo provedor, por exemplo provider-a:transaction-123",
                        "name": "Idempotency-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "A operação",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wagering.SubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wagering.TransactionResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/wagering.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/wagering.TransactionResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        },
        "/wagering/transactions/{transactionId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Permite acompanhar uma pendência (tentativas, próxima olhada e expiração) e consultar o código de uma rejeição ou falha. Uma transação de outro provedor responde 404, exatamente como uma que não existe: perguntar não revela de quem é.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wagering"
                ],
                "summary": "Lê uma transação pelo id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da transação",
                        "name": "transactionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wagering.TransactionDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        },
        "/wallets": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Cria a carteira na moeda do saldo inicial. Com saldo positivo, cria também a transação OPENING, o crédito no ledger e os eventos, no mesmo commit. Com saldo zero, cria só a carteira. Restrita ao serviço interno.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Abre a carteira de um jogador",
                "parameters": [
                    {
                        "description": "Jogador e saldo inicial",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wallet.OpenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/wallet.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        },
        "/wallets/{walletId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Devolve o saldo e a versão atuais. Restrita ao serviço interno.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Lê uma carteira",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da carteira",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wallet.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        },
        "/wallets/{walletId}/ledger": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Paginado por cursor opaco, do lançamento mais antigo para o mais novo. A ordem é a posição que o banco deu a cada lançamento, que não muda nem se repete: um lançamento gravado enquanto o cliente lê aparece numa página posterior, e nenhum é pulado nem visto duas vezes. Restrita ao serviço interno.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Lê o ledger de uma carteira",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da carteira",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cursor devolvido pela página anterior",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Tamanho da página, de 1 a 200. Padrão 50.",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wallet.LedgerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        },
        "/wallets/{walletId}/reconciliation": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Reconstrói o saldo a partir do ledger, abertura incluída, e compara com o saldo gravado, os dois lidos de uma mesma visão consistente dos dados. Não altera nada: uma divergência vai na resposta, no log e numa métrica, e nunca é corrigida. Restrita ao serviço interno.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Reconcilia uma carteira",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id da carteira",
                        "name": "walletId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wallet.ReconciliationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/structs.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.Readiness": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "unavailable"
                    ],
                    "example": "ok"
                }
            }
        },
        "health.Status": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "server"
                },
                "service": {
                    "type": "string",
                    "example": "pedro-test-server"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.4.0"
                }
            }
        },
        "structs.APIError": {
            "type": "object",
            "properties": {
                "failureCode": {
                    "description": "FailureCode is the stable, documented reason of a business rejection or of an invalid\noperation. It is what a provider reads to tell an input it can correct from a definitive\noutcome, and it is absent on errors that are not about the operation itself.",
                    "type": "string",
                    "example": "INSUFFICIENT_FUNDS"
                },
                "message": {
                    "type": "string",
                    "example": "invalid token"
                }
            }
        },
        "structs.MoneyDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "25.00"
                },
                "currency": {
                    "type": "string",
                    "example": "BRL"
                }
            }
        },
        "structs.Principal": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "provider_id": {
                    "description": "ProviderID is the provider this identity acts as, from the provider_id claim of its\ntoken. It is empty for anyone that is not a provider. The provider a request may act for\ncomes from here and never from what the request says about itself.",
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sub": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "wagering.SubmitRequest": {
            "type": "object",
            "properties": {
                "externalTransactionId": {
                    "type": "string",
                    "example": "transaction-123"
                },
                "gameId": {
                    "type": "string",
                    "example": "fortune-chimp"
                },
                "kind": {
                    "type": "string",
                    "enum": [
                        "BET",
                        "WIN",
                        "LOSS",
                        "REFUND",
                        "ROLLBACK"
                    ],
                    "example": "BET"
                },
                "money": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "playerId": {
                    "type": "string",
                    "example": "0192f28f-5dc0-7d58-bdb2-814ad6a0f4a1"
                },
                "providerId": {
                    "type": "string",
                    "example": "provider-a"
                },
                "referenceExternalTransactionId": {
                    "type": "string",
                    "example": "transaction-122"
                },
                "roundId": {
                    "type": "string",
                    "example": "round-987"
                },
                "walletId": {
                    "type": "string",
                    "example": "0192f291-27dd-7d3f-8071-5f8685deef37"
                }
            }
        },
        "wagering.TransactionDetail": {
            "type": "object",
            "properties": {
                "balance": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-09-08T12:00:00.000Z"
                },
                "expiresAt": {
                    "type": "string",
                    "example": "2026-09-09T12:00:00.000Z"
                },
                "externalTransactionId": {
                    "type": "string",
                    "example": "transaction-123"
                },
                "failureCode": {
                    "type": "string",
                    "example": "INSUFFICIENT_FUNDS"
                },
                "gameId": {
                    "type": "string",
                    "example": "fortune-chimp"
                },
                "kind": {
                    "type": "string",
                    "enum": [
                        "BET",
                        "WIN",
                        "LOSS",
                        "REFUND",
                        "ROLLBACK"
                    ],
                    "example": "BET"
                },
                "money": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "nextAttemptAt": {
                    "type": "string",
                    "example": "2026-09-08T12:00:05.000Z"
                },
                "playerId": {
                    "type": "string",
                    "example": "0192f28f-5dc0-7d58-bdb2-814ad6a0f4a1"
                },
                "providerId": {
                    "type": "string",
                    "example": "provider-a"
                },
                "referenceAttempts": {
                    "type": "integer",
                    "example": 3
                },
                "referenceExternalTransactionId": {
                    "type": "string",
                    "example": "transaction-122"
                },
                "roundId": {
                    "type": "string",
                    "example": "round-987"
                },
                "settledAt": {
                    "type": "string",
                    "example": "2026-09-08T12:00:00.000Z"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "PENDING",
                        "PENDING_REFERENCE",
                        "PROCESSED",
                        "REJECTED",
                        "FAILED"
                    ],
                    "example": "PROCESSED"
                },
                "transactionId": {
                    "type": "string",
                    "example": "0192f298-345e-7e38-af88-e43f851a819d"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-09-08T12:00:00.000Z"
                },
                "walletId": {
                    "type": "string",
                    "example": "0192f291-27dd-7d3f-8071-5f8685deef37"
                }
            }
        },
        "wagering.TransactionResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "failureCode": {
                    "type": "string",
                    "example": "INSUFFICIENT_FUNDS"
                },
                "idempotentReplay": {
                    "type": "boolean",
                    "example": false
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "PROCESSED",
                        "REJECTED",
                        "PENDING_REFERENCE",
                        "FAILED"
                    ],
                    "example": "PROCESSED"
                },
                "transactionId": {
                    "type": "string",
                    "example": "0192f298-345e-7e38-af88-e43f851a819d"
                }
            }
        },
        "wallet.LedgerEntryResponse": {
            "type": "object",
            "properties": {
                "balanceAfter": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "balanceBefore": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2026-09-08T12:00:00.000Z"
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "DEBIT",
                        "CREDIT"
                    ],
                    "example": "DEBIT"
                },
                "id": {
                    "type": "string",
                    "example": "0192f2a1-4d3e-7b1a-9c55-0f1e2d3c4b5a"
                },
                "money": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "transactionId": {
                    "type": "string",
                    "example": "0192f298-345e-7e38-af88-e43f851a819d"
                }
            }
        },
        "wallet.LedgerResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wallet.LedgerEntryResponse"
                    }
                },
                "nextCursor": {
                    "description": "NextCursor is absent on the last page. It is opaque: hand it back unchanged.",
                    "type": "string",
                    "example": "djEuNDI"
                }
            }
        },
        "wallet.OpenRequest": {
            "type": "object",
            "properties": {
                "initialBalance": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "playerId": {
                    "type": "string",
                    "example": "0192f28f-5dc0-7d58-bdb2-814ad6a0f4a1"
                }
            }
        },
        "wallet.ReconciliationResponse": {
            "type": "object",
            "properties": {
                "calculatedBalance": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "checkedEntries": {
                    "type": "integer",
                    "example": 2
                },
                "consistent": {
                    "type": "boolean",
                    "example": true
                },
                "difference": {
                    "description": "Difference is the stored balance minus the calculated one.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/structs.MoneyDTO"
                        }
                    ]
                },
                "storedBalance": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "walletId": {
                    "type": "string",
                    "example": "0192f291-27dd-7d3f-8071-5f8685deef37"
                }
            }
        },
        "wallet.Response": {
            "type": "object",
            "properties": {
                "balance": {
                    "$ref": "#/definitions/structs.MoneyDTO"
                },
                "id": {
                    "type": "string",
                    "example": "0192f291-27dd-7d3f-8071-5f8685deef37"
                },
                "playerId": {
                    "type": "string",
                    "example": "0192f28f-5dc0-7d58-bdb2-814ad6a0f4a1"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "http://localhost:8080/realms/pedro-test/protocol/openid-connect/token",
            "scopes": {
                "openid": "Acesso à API"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "pedro-test",
	Description:      "Carteiras de jogadores e operações de provedores de jogos: apostas, prêmios, derrotas, estornos e reversões.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
