//go:build e2e

package e2e

import (
	"net/http"
	"strings"
	"testing"

	"github.com/estrategiahq/pedro-test/app/test/e2e/core"
)

// Feature: API documentation
//
//   As someone integrating with this API
//   I want a page that describes every route and lets me call them
//   So that I can get a token and try a request without writing any code
//
//   The document is generated by swag from annotations next to each handler, so these scenarios
//   guard the two things generation does not: that the annotations describe the routes that are
//   really registered, and that the token URL served points at the realm the caller reaches
//   rather than the one the container reaches.
//
//   The routes are registered only when DOCS_ENABLED is on, which the suite turns on. With it
//   off nothing is registered, so there is nothing to forbid — which is why there is no
//   scenario for a 403 here.
//
//   Scenarios:
//     - the documentation page is served
//     - the document describes the routes that are served
//     - the document declares the Keycloak flow the page authenticates with
//     - the document marks the protected operations
//     - the service routes can be tried from the docs page with a pasted token

// Scenario: the documentation page is served
//
//	Given the documentation is enabled
//	When the Swagger UI is requested without a token
//	Then the server answers 200 with an HTML page
//
//	The page itself is public on purpose: it has to load before anyone can use it to get a
//	token. What it describes is protected by the routes themselves.
func TestDocumentationPageIsServed(t *testing.T) {
	res := stack.Request(t, http.MethodGet, "/swagger/index.html", "", nil)
	defer func() { _ = res.Body.Close() }()

	if res.StatusCode != http.StatusOK {
		t.Fatalf("expected the Swagger UI, got %d", res.StatusCode)
	}
	if contentType := res.Header.Get("Content-Type"); !strings.Contains(contentType, "text/html") {
		t.Fatalf("expected an HTML page, got %q", contentType)
	}
}

// Scenario: the document describes the routes that are served
//
//	Given the documentation is enabled
//	When the Swagger document is requested
//	Then every route this process serves is in it
//
//	This is the scenario that catches the failure mode of annotation-based docs: a route added
//	without its annotation is served and undocumented, and nothing else would notice.
func TestDocumentDescribesTheServedRoutes(t *testing.T) {
	document := swaggerDocument(t)

	for _, path := range []string{"/health", "/me"} {
		if _, ok := document.Paths[path]; !ok {
			t.Fatalf("path %s is missing from the Swagger document", path)
		}
	}
}

// Scenario: the document declares the Keycloak flow the page authenticates with
//
//	Given the documentation is enabled
//	When the Swagger document is requested
//	Then it declares an oauth2 password flow
//	And the token URL points at the realm as a browser reaches it
//
//	The last step is the one worth a test: swag bakes the URL at generation time, and the
//	application talks to Keycloak by its internal address. Serving either of those would break
//	the Authorize button for everyone outside the network.
func TestDocumentDeclaresTheKeycloakFlow(t *testing.T) {
	document := swaggerDocument(t)

	scheme, ok := document.SecurityDefinitions["OAuth2Password"]
	if !ok {
		t.Fatal("the OAuth2Password security definition is missing from the document")
	}
	if scheme.Type != "oauth2" || scheme.Flow != "password" {
		t.Fatalf("expected an oauth2 password flow, got %q/%q", scheme.Type, scheme.Flow)
	}
	if !strings.HasPrefix(scheme.TokenURL, stack.KeycloakURL) {
		t.Fatalf("token URL %q does not point at the realm the caller reaches (%s)",
			scheme.TokenURL, stack.KeycloakURL)
	}
}

// Scenario: the document marks the protected operations
//
//	Given the documentation is enabled
//	When the Swagger document is requested
//	Then the identity route requires the security scheme
//	And the probe requires nothing
func TestDocumentMarksTheProtectedOperations(t *testing.T) {
	document := swaggerDocument(t)

	if len(document.Paths["/me"]["get"].Security) == 0 {
		t.Fatal("GET /me is documented as public")
	}
	if len(document.Paths["/health"]["get"].Security) != 0 {
		t.Fatal("the probe is documented as protected, but it is open on purpose")
	}
}

// Scenario: the service routes can be tried from the docs page with a pasted token
//
//	Given the documentation is enabled
//	When the Swagger document is requested
//	Then it defines a BearerAuth scheme, an API key in the Authorization header
//	And every wallet and wagering route accepts either that scheme or the password grant
//
// The password grant of the page logs in a person, and no person of the realm holds a service
// role, so without the second scheme those routes could not be exercised from the page at all.
func TestTheServiceRoutesAcceptAPastedToken(t *testing.T) {
	document := swaggerDocument(t)

	bearer, ok := document.SecurityDefinitions["BearerAuth"]
	if !ok || bearer.Type != "apiKey" || bearer.In != "header" || bearer.Name != "Authorization" {
		t.Fatalf("BearerAuth = %+v (defined: %v)", bearer, ok)
	}
	for _, route := range []struct{ path, method string }{
		{"/wallets", "post"}, {"/wallets/{walletId}", "get"}, {"/wallets/{walletId}/ledger", "get"},
		{"/wallets/{walletId}/reconciliation", "post"}, {"/wagering/transactions", "post"},
		{"/wagering/transactions/{transactionId}", "get"},
		{"/providers/{providerId}/wagering/transactions/{externalTransactionId}", "get"},
	} {
		alternatives := document.Paths[route.path][route.method].Security
		if len(alternatives) != 2 || !offers(alternatives, "OAuth2Password") || !offers(alternatives, "BearerAuth") {
			t.Errorf("%s %s security = %v, want the password grant or a pasted bearer token", route.method, route.path, alternatives)
		}
	}
}

func offers(alternatives []map[string][]string, scheme string) bool {
	for _, alternative := range alternatives {
		if _, ok := alternative[scheme]; ok {
			return true
		}
	}
	return false
}

// swagger is a deliberately small shape: the suite asserts on the few fields that say what is
// served and what is protected, not on the whole document.
type swagger struct {
	Paths map[string]map[string]struct {
		Security []map[string][]string `json:"security"`
	} `json:"paths"`
	SecurityDefinitions map[string]struct {
		Type     string `json:"type"`
		Flow     string `json:"flow"`
		TokenURL string `json:"tokenUrl"`
		In       string `json:"in"`
		Name     string `json:"name"`
	} `json:"securityDefinitions"`
}

func swaggerDocument(t *testing.T) swagger {
	t.Helper()

	res := stack.Request(t, http.MethodGet, "/swagger/doc.json", "", nil)
	if res.StatusCode != http.StatusOK {
		_ = res.Body.Close()
		t.Fatalf("expected the Swagger document, got %d", res.StatusCode)
	}
	return core.Decode[swagger](t, res)
}
